export const PROJECT_DATA = {
  DriveXperience: {
    id: 'DriveXperience',
    name: 'DriveXperience',
    images: [
      'drivexperience_thumbnail.webp',
      'drivexperience_banner.webp',
      'drivexperience_coche1.webp',
      'drivexperience_coche2.webp',
      'drivexperience_home.webp',
      'drivexperience_login.webp',
      'drivexperience_reservas.webp',
      'drivexperience_reservas_done.webp',
    ],
    tags: ['Angular', 'HTML', 'CSS', 'TypeScript', 'MySql', 'Java', 'Spring Boot', 'Azure'],
    links: {
      project: 'https://drivexperience.azurewebsites.net/',
      github: 'https://github.com/CristopherJmnz/DriveXperience-Angular',
    },
  },
  SkyAir: {
    id: 'SkyAir',
    name: 'SkyAir',
    images: [
      'skyair_thumbnail.webp',
      'skyair_vuelos.webp',
      'skyair_asientos.webp',
      'skyair_billete.webp',
    ],
    tags: [
      'HTML',
      'C#',
      'Entity Framework',
      'Azure',
      'SQL Server',
      '.NET',
      'JavaScript',
      'Bootstrap',
    ],
    links: {
      project: 'https://mvcskyair.azurewebsites.net/',
      github: 'https://github.com/CristopherJmnz/MvcSkyAir',
    },
  },
  ServiciosyReparacionesPatricio: {
    id: 'ServiciosyReparacionesPatricio',
    name: 'Servicios y Reparaciones Patricio',
    images: [
      'serviciosyreparaciones-thumbnail.webp',
      'serviciosyreparaciones-home-2.webp',
      'serviciosyreparaciones-reforma-integral.webp',
      'serviciosyreparaciones-form-presupuesto.webp',
      'serviciosyreparaciones-reforma-cocina.webp',
    ],
    tags: ['Angular', 'TypeScript', 'HTML', 'CSS', 'Bootstrap', 'EmailJs', 'Vercel'],
    links: {
      project: 'https://serviciosyreparacionespatricio.es/',
      github: 'https://github.com/CristopherJmnz/ReformasPatricioWeb',
    },
  },
  Techriders: {
    id: 'Techriders',
    name: 'Tech Riders',
    images: [
      'techriders_thumbnail.webp',
      'techriders_empresas.webp',
      'techriders_solicitud.webp',
      'techriders_users.webp',
      'techriders_calendario.webp',
      'techriders_landing.webp',
    ],
    tags: [
      'Angular',
      'TypeScript',
      'JavaScript',
      'HTML',
      'CSS',
      'Bootstrap',
      'SQL Server',
      'Azure',
    ],
    links: {
      project: 'https://github.com/CristopherJmnz/techridersapp',
      github: 'https://github.com/CristopherJmnz/techridersapp',
    },
  },
  Wordle: {
    id: 'Wordle',
    name: 'Wordle',
    images: ['wordle_thumbnail.webp', 'wordle_light.webp'],
    tags: ['HTML', 'CSS', 'JavaScript', 'Vercel'],
    links: {
      project: 'https://wordle-one-flame.vercel.app/',
      github: 'https://github.com/CristopherJmnz/WORDLE-NORMAL-AMC-CJJ',
    },
  },
  ApiSkyAir: {
    id: 'ApiSkyAir',
    name: 'Api SkyAir',
    images: ['apiskyair_swagger.webp'],
    tags: ['C#', '.NET', 'Entity Framework', 'Azure', 'SQL Server', 'Swagger'],
    links: {
      project: 'https://skyairapi.azurewebsites.net/index.html',
      github: 'https://github.com/CristopherJmnz/SkyAirApi',
    },
  },
};
